package com.nerduino.processing.app;

import com.nerduino.library.NerduinoBase;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.openide.windows.IOProvider;
import org.openide.windows.InputOutput;

public class CompileCommand extends java.awt.Panel implements ICompileCallback, IBuildTask
{
	NerduinoBase m_nerduino;
	
	boolean m_success = false;
	int m_errors = 0;
	CompileCommand m_command;
	boolean m_busy = false;
	
	public CompileCommand(NerduinoBase nerduino)
	{
		initComponents();
		
		m_nerduino = nerduino;
		m_command = this;
	}

	@Override
	public void validate()
	{
		super.validate();
		
		jProgressBar1.setSize(this.getWidth(), 18);
	}
	
	public void setEngaged(boolean engaged)
	{
		if (engaged)
			setIcon(engageButton, "/com/nerduino/resources/EngageSucceed16.png");
		else
			setIcon(engageButton, "/com/nerduino/resources/EngageFailed16.png");
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        compileButton = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        engageButton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(2147483647, 22));
        setMinimumSize(new java.awt.Dimension(16, 22));
        setPreferredSize(new java.awt.Dimension(60, 22));
        setSize(new java.awt.Dimension(60, 22));
        setLayout(null);

        compileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nerduino/resources/Check16.png"))); // NOI18N
        compileButton.setToolTipText(org.openide.util.NbBundle.getMessage(CompileCommand.class, "CompileCommand.compileButton.toolTipText")); // NOI18N
        compileButton.setBorderPainted(false);
        compileButton.setContentAreaFilled(false);
        compileButton.setIconTextGap(0);
        compileButton.setLabel(org.openide.util.NbBundle.getMessage(CompileCommand.class, "CompileCommand.compileButton.label")); // NOI18N
        compileButton.setMaximumSize(new java.awt.Dimension(18, 18));
        compileButton.setMinimumSize(new java.awt.Dimension(18, 18));
        compileButton.setPreferredSize(new java.awt.Dimension(18, 18));
        compileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                OnCompileAction(evt);
            }
        });
        add(compileButton);
        compileButton.setBounds(0, 0, 20, 18);

        uploadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nerduino/resources/Upload16.png"))); // NOI18N
        uploadButton.setToolTipText(org.openide.util.NbBundle.getMessage(CompileCommand.class, "CompileCommand.uploadButton.toolTipText")); // NOI18N
        uploadButton.setBorderPainted(false);
        uploadButton.setContentAreaFilled(false);
        uploadButton.setIconTextGap(0);
        uploadButton.setLabel(org.openide.util.NbBundle.getMessage(CompileCommand.class, "CompileCommand.uploadButton.label")); // NOI18N
        uploadButton.setMaximumSize(new java.awt.Dimension(18, 18));
        uploadButton.setMinimumSize(new java.awt.Dimension(18, 18));
        uploadButton.setPreferredSize(new java.awt.Dimension(18, 18));
        uploadButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                OnUploadAction(evt);
            }
        });
        add(uploadButton);
        uploadButton.setBounds(20, 0, 20, 18);

        engageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nerduino/resources/EngageUnknown16.png"))); // NOI18N
        engageButton.setToolTipText(org.openide.util.NbBundle.getMessage(CompileCommand.class, "CompileCommand.engageButton.toolTipText")); // NOI18N
        engageButton.setBorderPainted(false);
        engageButton.setBounds(new java.awt.Rectangle(40, 1, 20, 18));
        engageButton.setContentAreaFilled(false);
        engageButton.setIconTextGap(0);
        engageButton.setLabel(org.openide.util.NbBundle.getMessage(CompileCommand.class, "CompileCommand.engageButton.label")); // NOI18N
        engageButton.setMaximumSize(new java.awt.Dimension(18, 18));
        engageButton.setMinimumSize(new java.awt.Dimension(18, 18));
        engageButton.setPreferredSize(new java.awt.Dimension(18, 18));
        engageButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                OnEngageAction(evt);
            }
        });
        add(engageButton);
        engageButton.setBounds(40, 0, 20, 18);

        jProgressBar1.setBorder(null);
        jProgressBar1.setBorderPainted(false);
        add(jProgressBar1);
        jProgressBar1.setBounds(0, 0, 60, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void OnCompileAction(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OnCompileAction
    {//GEN-HEADEREND:event_OnCompileAction
		if (!m_busy)
		{
			Thread thread = new Thread(new Runnable()
			{
				@Override
				public void run()
				{
					m_success = false;
					m_errors = 0;
					m_busy = true;

					setIcon(compileButton, "/com/nerduino/resources/Check16.png");
					setIcon(uploadButton, "/com/nerduino/resources/UploadUnknown16.png");
					setIcon(engageButton, "/com/nerduino/resources/EngageUnknown16.png");
					
					Preferences.set("target", "arduino");

					Board board = BoardManager.Current.getBoard(m_nerduino.getBoardType());

					Preferences.set("board", board.getShortName());

					Sketch sketch = SketchManager.Current.getSketch(m_nerduino.getSketch());

					sketch.compile((ICompileCallback) m_command);

					setProgress(0);

					if (!m_success)
					{
						setStatus("Compile Error!");
						setCompileSuccess(false);
						
						setIcon(compileButton, "/com/nerduino/resources/CheckFailed16.png");
					}
					else
					{
						setIcon(compileButton, "/com/nerduino/resources/CheckSucceed16.png");						
					}
					
					m_busy = false;
				}
			});

			thread.start();
		}
    }//GEN-LAST:event_OnCompileAction

    private void OnUploadAction(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OnUploadAction
    {//GEN-HEADEREND:event_OnUploadAction
		if (!m_busy)
		{
			Thread thread = new Thread(new Runnable()
			{
				@Override
				public void run()
				{
					m_busy = true;

					InputOutput io = IOProvider.getDefault().getIO("Build", false);

					m_success = false;
					m_errors = 0;

					setIcon(compileButton, "/com/nerduino/resources/Check16.png");
					setIcon(uploadButton, "/com/nerduino/resources/UploadUnknown16.png");
					setIcon(engageButton, "/com/nerduino/resources/EngageUnknown16.png");

					Preferences.set("target", "arduino");

					Board board = BoardManager.Current.getBoard(m_nerduino.getBoardType());

					Preferences.set("board", board.getShortName());

					Sketch sketch = SketchManager.Current.getSketch(m_nerduino.getSketch());

					sketch.compile((ICompileCallback) m_command);

					if (m_success)
					{
						setIcon(compileButton, "/com/nerduino/resources/CheckSucceed16.png");

						setProgress(0);
						
						io.getOut().print("Uploading to " + m_nerduino.getName());

						String message = m_nerduino.upload(sketch);				
						
						boolean success = (message == null);

						setCompileSuccess(success);

						if (success)
						{
							io.getOut().println(" Complete!");
							setStatus("Uploade Complete!");
							
							setIcon(uploadButton, "/com/nerduino/resources/UploadSucceed16.png");
						}
						else
						{
							io.getOut().println(" Failed!");
							io.getErr().println(message);

							setStatus("Uploade Failed!");
							
							setIcon(uploadButton, "/com/nerduino/resources/UploadFailed16.png");
						}
					}
					
					setProgress(0);
					
					m_busy = false;
					
					OnEngageAction(null);
				}
			});

			thread.start();
		}
    }//GEN-LAST:event_OnUploadAction

    private void OnEngageAction(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OnEngageAction
    {//GEN-HEADEREND:event_OnEngageAction
		if (!m_busy)
		{
			m_busy = true;
			
			setIcon(engageButton, "/com/nerduino/resources/EngageUnknown16.png");

			InputOutput io = IOProvider.getDefault().getIO("Build", false);
			io.getOut().print("Engaging " + m_nerduino.getName());
			
			String message = m_nerduino.engage((IBuildTask) this);
			
			m_success = (message == null);
			
			if (m_success)
			{
				io.getOut().println(" Complete!");
				
				setCompileSuccess(true);
				setProgress(0);
				setIcon(engageButton, "/com/nerduino/resources/EngageSucceed16.png");
			}
			else
			{
				io.getOut().println(" Failed!");
				
				if (message != null)
					io.getErr().println(message);
				
				setCompileSuccess(false);
				setProgress(0);
				setIcon(engageButton, "/com/nerduino/resources/EngageFailed16.png");
			}
			
			m_busy = false;
		}
    }//GEN-LAST:event_OnEngageAction

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compileButton;
    private javax.swing.JButton engageButton;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables

	@Override
	public void setProgress(int progress)
	{
		jProgressBar1.setValue(progress);
		jProgressBar1.paintImmediately(0, 0, 60, 20);
	}

	@Override
	public void setCompileSuccess(boolean success)
	{
		m_success = success;
	}
	
	void setIcon(JButton button, String path)
	{
		java.net.URL imgURL = getClass().getResource(path);
		
		if (imgURL != null)
		{
			button.setIcon(new ImageIcon(imgURL));
		}
	}

	@Override
	public void setErrorCount(int count)
	{
		m_errors = count;
	}

	@Override
	public void setStatus(String status)
	{
	}	

	@Override
	public void configure(Sketch sketch, NerduinoBase nerduino)
	{
	}

	@Override
	public void execute()
	{
	}

	@Override
	public void setSuccess(boolean success)
	{
	}

	@Override
	public boolean isSelected()
	{
		return true;
	}

	@Override
	public void reset()
	{
	}
}
