/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nerduino.core;

import com.nerduino.nodes.RootNode;
import com.nerduino.nodes.TreeNode;
import java.beans.PropertyVetoException;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.JFrame;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.actions.CopyAction;
import org.openide.actions.CutAction;
import org.openide.actions.DeleteAction;
import org.openide.actions.PasteAction;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.WeakListeners;
import org.openide.util.actions.SystemAction;
import org.openide.windows.Mode;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.pushingpixels.flamingo.api.ribbon.JRibbon;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//com.nerduino.core//Explorer//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "ExplorerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.nerduino.core.ExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_ExplorerAction",
preferredID = "ExplorerTopComponent")
@Messages(
{
	"CTL_ExplorerAction=Explorer",
	"CTL_ExplorerTopComponent=Explorer",
	"HINT_ExplorerTopComponent=This is the Explorer window"
})
public final class ExplorerTopComponent extends TopComponent
		implements ExplorerManager.Provider, LookupListener
{
	private static final String ROOT_NODE = "Explorer";
	private final ExplorerManager m_manager = new ExplorerManager();
	public static ExplorerTopComponent Current;
	Node m_rootNode;
	private Lookup.Result<TreeNode> m_result;
	private LookupListener weakLookup;
	TreeNode m_currentSelection;
	
	static JRibbon s_ribbon;

	public ExplorerTopComponent()
	{
		Current = this;

		initComponents();
		setName(Bundle.CTL_ExplorerTopComponent());
		setToolTipText(Bundle.HINT_ExplorerTopComponent());
		putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
		putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);

		// Initialize the application manager
		AppManager.initialize();

		initComponents();

		m_rootNode = new RootNode();
		m_manager.setRootContext(m_rootNode);

		beanTreeView1.setRootVisible(false);

		Lookup lookup = ExplorerUtils.createLookup(m_manager, getActionMap());

		associateLookup(lookup);

		m_result = lookup.lookupResult(TreeNode.class);
		weakLookup = WeakListeners.create(LookupListener.class, this, m_result);
		m_result.addLookupListener(weakLookup);

		AppManager.Current.initializeExplorer();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beanTreeView1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beanTreeView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables

	@Override
	public void componentOpened()
	{
		// TODO add custom code on component opening
		
		// convenient time to get the instance of the jribbon class
		JFrame frame = (JFrame) WindowManager.getDefault().getMainWindow();
		
		AppManager.Current.setRibbon((JRibbon) frame.getRootPane().getLayeredPane().getComponent(0));
		
 	}

	@Override
	public void componentClosed()
	{
		// TODO add custom code on component closing
	}

	@Override
	public void open()
	{
		Mode m = WindowManager.getDefault().findMode("explorer");

		if (m != null)
		{
			m.dockInto(this);
		}

		super.open();
	}

	public TreeNode getSelectedNode()
	{
		return m_currentSelection;
	}
	
	public void setSelectedNode(TreeNode node)
	{
		
		Node[] nodes = new Node[] { node };
		
		try
		{
			m_manager.setExploredContextAndSelection(node, nodes);
		}
		catch(PropertyVetoException ex)
		{
			//Exceptions.printStackTrace(ex);
		}
	}

	@Override
	protected void componentActivated()
	{
		ExplorerUtils.activateActions(m_manager, true);
	}

	@Override
	protected void componentDeactivated()
	{
		ExplorerUtils.activateActions(m_manager, false);
	}

	@Override
	public ExplorerManager getExplorerManager()
	{
		return m_manager;
	}

	private void initActions()
	{
		CutAction cut = SystemAction.get(CutAction.class);
		getActionMap().put(cut.getActionMapKey(), ExplorerUtils.actionCut(m_manager));
		CopyAction copy = SystemAction.get(CopyAction.class);
		getActionMap().put(copy.getActionMapKey(), ExplorerUtils.actionCopy(m_manager));
		PasteAction paste = SystemAction.get(PasteAction.class);
		getActionMap().put(paste.getActionMapKey(), ExplorerUtils.actionPaste(m_manager));
		DeleteAction delete = SystemAction.get(DeleteAction.class);
		getActionMap().put(delete.getActionMapKey(), ExplorerUtils.actionDelete(m_manager, true));
	}

	void writeProperties(java.util.Properties p)
	{
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p)
	{
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}

	void addNode(Node node)
	{
		Node nodes[] = new Node[1];

		nodes[0] = node;

		m_rootNode.getChildren().add(nodes);
	}

	public Node getRootNode()
	{
		return m_rootNode;
	}

	void clearTree()
	{
		beanTreeView1.removeAll();
	}

	void expandAll()
	{
		beanTreeView1.expandAll();
	}
	
	void expandNode(Node node)
	{
		beanTreeView1.expandNode(node);
	}


	@Override
	public void resultChanged(LookupEvent lookupEvent)
	{
		Lookup.Result r = (Lookup.Result) lookupEvent.getSource();

		Collection c = r.allInstances();
		TreeNode node = null;

		if (!c.isEmpty())
		{
			Object[] objs = c.toArray();

			for (Iterator it = c.iterator(); it.hasNext();)
			{
				Object obj = it.next();


				if (obj instanceof TreeNode)
				{
					node = (TreeNode) obj;
					break;
				}
			}
		}

		if (node != m_currentSelection)
		{
			if (m_currentSelection != null)
			{
				m_currentSelection.onDeselected();
			}

			m_currentSelection = node;

			if (m_currentSelection != null)
			{
				m_currentSelection.onSelected();
			}
		}
	}
}
